### ISSUE TITLE
FR add cpu temperature 

### ISSUE THREAD

**Issue by Mariusthvdb** [adamoutler/HassOSArgonOneAddon#14]
please consider adding the measured temp to the attributes of the fan_speed sensor, or, even nicer, create a dedicated entity for it?

I've have 2 cpu sensors (the well known command_line sensor, and the processor_temperature of system monitor) and they all vary somewhat. Trying to be as precise as possible, and set the correct thresholds for the fan speed, it would help to have the core temp sensor of this add-on too.

Since it is already available to the add-on (and can optionally even be outputted in the log) I would hope this to be a feasible FR? 

thanks for considering

**Comment by adamoutler** [comment]
Added
![image](https://user-images.githubusercontent.com/527919/125176759-26fe0580-e1a4-11eb-9f2a-9ce3da9796ab.png)
The attribute will be Temperature F or Temperature C, depending on which one you use.

**Comment by Mariusthvdb** [comment]
thx! very much appreciated!

will this appear as an update on the add-on?

**Comment by adamoutler** [comment]
Yep.  V23 is published. Update the supervisor apps and it will show up.

**Comment by Mariusthvdb** [comment]
Thanks, and see it. But.... does this really only update per 10 minutes?

**Comment by adamoutler** [comment]
No. It updates on each change and every 10 minutes.

**Comment by Mariusthvdb** [comment]
thanks, I was confused by the description in the changes, and created this meanwhile:

```
      - type: custom:multiple-entity-row
        entity: sensor.argon_one_addon_fan_speed
        secondary_info: last-changed
        entities:
          - attribute: Temperature C
            name: Temp
            unit: '°C'
          - attribute: mode
            name: Mode
          - attribute: fan level
            name: Level

      - type: custom:template-entity-row
        entity: sensor.argon_one_addon_fan_speed
        state: >
          {{states(config.entity)}} %
        secondary: >
          {{relative_time(states.sensor.argon_one_addon_fan_speed.last_changed)}} ago - Temp: {{state_attr(config.entity,'Temperature C')}} °C, Mode: {{state_attr(config.entity,'mode')}}, Level: {{state_attr(config.entity,'fan level')}}
      - entity: sensor.argon_one_addon_fan_speed
        secondary_info: last-changed
        card_mod:
          style: |
            :host {
              --paper-item-icon-color:
                  {% set speed = states(config.entity)|int %}
                  {% set mapper = {0:'green',1:'darkgreen',3:'orange',
                  33:'orangered',66:'maroon'} %}
                  {{ mapper[speed] if speed in mapper else 'red'}}
              }
      - entity: sensor.argon_one_cpu_temperature
        secondary_info: last-changed
```

bottom sensor is a template sensor on the attribute.

so I already noticed it change faster than per 10 minutes ;-)

<img width="480" alt="Schermafbeelding 2021-07-14 om 13 46 59" src="https://user-images.githubusercontent.com/33354141/125616951-d4d4c8d6-8733-4106-ab5a-3206acd604dc.png">

**Comment by adamoutler** [comment]
I think that looks great!

If you'd like, I also have a dedicated CPU Temp addon.   This one is primarily concerned with keeping CPU temp within ranges.  Design decisions for this project were to use entirely BASH to keep the script in memory without any external process needing to be launched except to make changes with `i2c-set`.  People wanted reporting, so netcat `nc` was chosen to make requests because of its footprint and processing compared to `wget` or `curl`.  People had problems because it wouldn't change frequently enough, so a timer was added.  If you want more accurate/up-to-date info, there are integrations which can `cat`, or `read` the sensor then perform a math operation.  The reason you'd want this one is it will almost never exceed 1% processor usage after startup and the RAM footprint is small.

**Comment by Mariusthvdb** [comment]
of course I had the command_line sensor
```
command: >      cat /sys/class/thermal/thermal_zone0/temp
```
before. Also, there  is the system_monitor sensor, which has a somewhat higher temp than your add-on. Not sure what to do now, because as you say, I am mostly interested in keeping the temp within ranges. 

btw, I dont have a `read` sensor, which would the be?

between both of your add-ons, what's the main difference? I believed the Argon One add-on to also do what the Temp add-on does?

**Comment by adamoutler** [comment]
`cat` and `read` can perform the same functions.  The difference is `cat` is an external binary which requires a new process, loading the binary, and then executing.   `read` is a bash built-in, so it just executes within the bash process.   To get a value from a file into a variable and then echo the contents of that variable with `cat`
`myvar=$(cat /path/to/device); echo ${myvar};`
With `read` it's not as obvious
`read -r myvar</path/to/device; echo ${myvar};`

Functionally these two are equal, but `read` executes in between 0 and 8ms, and `cat` depends on the system, between 0-40ms.  Additionally there is very little system utilization with `read`.

`cat` is primarily intended to conCATenate multiple files together like `cat 1.txt 2.txt 3.txt>my.txt` and nothing does it better.  `read` is intended to take input from the command line and place it into a file.  But on Linux, everything, even user input, is a file so redirecting from the default input `/proc/<pid>/fd/3`  to the system device you want `/path/to/device` is a trivial task to accomplish.

As for the difference between these add-ons, CPU Temp reports temp to UI every 30seconds.  ArgonOne has the same core, but regulates temperature and only reports on change or 10 minutes.

**Comment by Mariusthvdb** [comment]
wow, thanks for this! will check up on that `read`

for speed's sake, would this be the correct format using the command_line:

```
sensor:
  - platform: command_line
    command: read -r /sys/class/thermal/thermal_zone0/temp
    value_template: >
      {{value|multiply(0.001)|round(1)}}
```

if the cat version is:

```
  - platform: command_line
    name: Cpu temperature
    command: >
      cat /sys/class/thermal/thermal_zone0/temp
    unit_of_measurement: °C
    value_template: >
      {{value|multiply(0.001)|round(1)}}
```
?
